import os
import re
from pathlib import Path

from secret_redaction import redact_text
from strata.core.brief_impact import generate_impact_notes
from strata.utils.prompt_safety import UNTRUSTED_CONTENT_WARNING, wrap_repository_content
from strata.utils.artifacts import write_artifact_output_path


TASK_WORD_STOP_WORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from",
    "in", "into", "is", "it", "of", "on", "or", "the", "this", "to",
    "with",
}

SYMBOL_MATCH_STOP_WORDS = {
    "add", "fix", "change", "update", "remove", "create", "make",
    "command", "commands", "test", "tests", "testing",
}


def generate_task_brief(graph: dict, task: str, max_files: int = 5) -> str:
    """Generate a task-specific Markdown brief from a Strata graph."""

    task = redact_text(task)
    scored_files = score_relevant_files(graph, task)
    relevant_files = scored_files[:max_files]

    lines = []

    lines.append("# Task Brief")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append(UNTRUSTED_CONTENT_WARNING)
    lines.append("")
    lines.append("## Task")
    lines.append("")
    lines.append(task)
    lines.append("")
    repository_context_start = len(lines)
    lines.append("## Repository Summary")
    lines.append("")
    lines.append(f"- Project root: `{graph.get('root', '')}`")
    lines.append(f"- Schema version: `{graph.get('schema_version', '')}`")
    lines.append(f"- Files scanned: `{len(graph.get('files', []))}`")
    lines.append(f"- Dependency edges: `{len(graph.get('edges', []))}`")
    lines.append("")
    lines.append("## Relevant Files")
    lines.append("")

    if relevant_files:
        for index, item in enumerate(relevant_files, start=1):
            file_info = item["file"]
            score = item["score"]
            reason = explain_relevance(file_info, task)

            lines.append(f"{index}. `{file_info['path']}`")
            lines.append(f"   - Relevance score: `{score}`")
            lines.append(f"   - Reason: {reason}")
    else:
        lines.append("No strongly relevant files found.")

    lines.append("")
    lines.append("## File Context")
    lines.append("")

    if relevant_files:
        for item in relevant_files:
            file_info = item["file"]
            lines.extend(_format_file_context(file_info, graph))
            lines.append("")
    else:
        lines.append("No file context available.")
        lines.append("")

    lines.append(generate_impact_notes(graph, relevant_files))
    lines.append("")

    lines.append("## Risks")
    lines.append("")

    risks = generate_risks(relevant_files)

    if risks:
        for risk in risks:
            lines.append(f"- {risk}")
    else:
        lines.append("- No obvious risks detected from the current graph.")

    lines.append("")
    lines.append("## Suggested Tests")
    lines.append("")

    tests = suggest_tests(relevant_files)

    if tests:
        for test in tests:
            lines.append(f"- `{test}`")
    else:
        lines.append("- `py tests.py`")

    lines.append("")
    repository_lines = lines[repository_context_start:]
    lines[repository_context_start:] = wrap_repository_content(repository_lines)
    lines.append("## Suggested Prompt for AI Agent")
    lines.append("")
    lines.append("Use this prompt with your coding assistant:")
    lines.append("")
    lines.append("```text")
    lines.append(f"Task: {task}")
    lines.append("")
    lines.append(UNTRUSTED_CONTENT_WARNING)
    lines.append("")
    prompt_repository_lines = ["Read these files first:"]

    if relevant_files:
        for item in relevant_files:
            prompt_repository_lines.append(f"- {item['file']['path']}")
    else:
        prompt_repository_lines.append("- No specific files selected. Inspect the project map first.")

    prompt_repository_lines.append("")
    lines.extend(wrap_repository_content(prompt_repository_lines))
    lines.append("Follow these rules:")
    lines.append("- Use only the Python standard library.")
    lines.append("- Do not touch unrelated files.")
    lines.append("- Preserve existing CLI behavior unless the task requires changing it.")
    lines.append("- Run the suggested tests before finishing.")
    lines.append("```")

    return redact_text("\n".join(lines).rstrip() + "\n")


def write_task_brief(graph: dict, task: str, output_path: str) -> None:
    """Write a task-specific brief to disk."""

    content = generate_task_brief(graph, task)

    if ".aidc" in Path(output_path).parts:
        write_artifact_output_path(output_path, redact_text(content))
        return

    directory = os.path.dirname(output_path)
    if directory:
        os.makedirs(directory, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(redact_text(content))


def score_relevant_files(graph: dict, task: str) -> list[dict]:
    """Score files by how relevant they appear to be for a task."""

    task_words = _task_words(task)
    scored_files = []

    for file_info in graph.get("files", []):
        score = 0
        path = file_info.get("path", "")
        basename = os.path.basename(path)
        path_text = _normalize_text(path)
        basename_text = _normalize_text(basename)

        for word in task_words:
            if word in path_text:
                score += 5

            if word in basename_text:
                score += 4
        
        if "command" in task_words and basename == "cli.py":
            score += 8

        if "commands" in task_words and basename == "cli.py":
            score += 8

        if "cli" in task_words and basename == "cli.py":
            score += 8

        for class_info in file_info.get("classes", []):
            class_name = _normalize_text(class_info.get("name", ""))

            for word in task_words:
                if word in SYMBOL_MATCH_STOP_WORDS:
                    continue

                if word in class_name:
                    score += 3

        for function_info in file_info.get("functions", []):
            function_name = _normalize_text(function_info.get("name", ""))

            for word in task_words:
                if word in SYMBOL_MATCH_STOP_WORDS:
                    continue

                if word in function_name:
                    score += 3

        for import_name in file_info.get("imports", []):
            import_text = _normalize_text(import_name)

            for word in task_words:
                if word in SYMBOL_MATCH_STOP_WORDS:
                    continue

                if word in import_text:
                    score += 1

        if score:
            scored_files.append(
                {
                    "file": file_info,
                    "score": score,
                }
            )

    scored_files.sort(
        key=lambda item: (
            item["score"],
            os.path.basename(item["file"].get("path", "")),
        ),
        reverse=True,
    )

    return scored_files


def explain_relevance(file_info: dict, task: str) -> str:
    """Explain why a file was selected."""

    task_words = _task_words(task)
    path = file_info.get("path", "")
    basename = os.path.basename(path)

    path_text = _normalize_text(path)
    basename_text = _normalize_text(basename)

    matched_path_words = [
        word for word in task_words
        if word in path_text or word in basename_text
    ]

    matched_symbols = []

    for class_info in file_info.get("classes", []):
        name = class_info.get("name", "")
        normalized_name = _normalize_text(name)

        for word in task_words:
            if word in SYMBOL_MATCH_STOP_WORDS:
                continue

            if word in normalized_name:
                matched_symbols.append(name)

    for function_info in file_info.get("functions", []):
        name = function_info.get("name", "")
        normalized_name = _normalize_text(name)

        for word in task_words:
            if word in SYMBOL_MATCH_STOP_WORDS:
                continue

            if word in normalized_name:
                matched_symbols.append(name)

    reasons = []

    if matched_path_words:
        reasons.append(
            "path matched task word(s): "
            + ", ".join(f"`{word}`" for word in sorted(set(matched_path_words)))
        )

    if matched_symbols:
        reasons.append(
            "symbol matched task language: "
            + ", ".join(f"`{name}`" for name in sorted(set(matched_symbols)))
        )

    if file_info.get("unresolved_imports"):
        reasons.append("file has unresolved imports that may need attention")

    if not reasons:
        return "connected to the task by repository context"

    return "; ".join(reasons)


def generate_risks(relevant_files: list[dict]) -> list[str]:
    """Generate simple risk notes for relevant files."""

    risks = []

    for item in relevant_files:
        file_info = item["file"]
        path = file_info.get("path", "")

        if file_info.get("unresolved_imports"):
            unresolved = ", ".join(file_info["unresolved_imports"])
            risks.append(f"`{path}` has unresolved import(s): `{unresolved}`.")

        if file_info.get("error"):
            risks.append(f"`{path}` has a parse error and may need manual inspection.")

        if path.endswith("cli.py"):
            risks.append("Changes to `cli.py` may affect user-facing commands.")

        if path.endswith("scanner.py"):
            risks.append("Changes to `scanner.py` may affect graph generation.")

        if path.endswith("brief.py"):
            risks.append("Changes to `brief.py` may affect generated task briefs.")

        if path.endswith("map_writer.py"):
            risks.append("Changes to `map_writer.py` may affect project map output.")

    return _dedupe(risks)


def suggest_tests(relevant_files: list[dict]) -> list[str]:
    """Suggest commands to verify a task."""

    tests = ["py tests.py"]

    paths = [
        item["file"].get("path", "")
        for item in relevant_files
    ]

    basenames = {
        os.path.basename(path)
        for path in paths
    }

    if "cli.py" in basenames:
        tests.append("strata help")

    if "scanner.py" in basenames:
        tests.append("strata scan tmp_repo")

    if "map_writer.py" in basenames:
        tests.append("strata map tmp_repo")

    if "brief.py" in basenames:
        tests.append('strata brief "add map command tests"')

    if "cycles.py" in basenames:
        tests.append("strata cycles tmp_repo")

    if "health.py" in basenames:
        tests.append("strata health tmp_repo")

    if "impact.py" in basenames:
        tests.append("strata impact tmp_repo helper.py")

    return _dedupe(tests)


def _format_file_context(file_info: dict, graph: dict) -> list[str]:
    lines = []

    path = file_info.get("path", "")

    lines.append(f"### `{path}`")
    lines.append("")
    lines.append(f"- Language: `{file_info.get('language', '')}`")

    classes = [
        item.get("name", "")
        for item in file_info.get("classes", [])
    ]

    functions = [
        item.get("name", "")
        for item in file_info.get("functions", [])
    ]

    lines.append(f"- Classes: {_format_inline_list(classes)}")
    lines.append(f"- Functions: {_format_inline_list(functions)}")
    lines.append(f"- Imports: {_format_inline_list(file_info.get('imports', []))}")
    lines.append(f"- External imports: {_format_inline_list(file_info.get('external_imports', []))}")

    unresolved_details = file_info.get("unresolved_import_details", [])

    if unresolved_details:
        unresolved = []

        for item in unresolved_details:
            unresolved.append(f"{item.get('name', '')} at line {item.get('line', '')}")

        lines.append(f"- Unresolved imports: {_format_inline_list(unresolved)}")
    else:
        lines.append("- Unresolved imports: none")

    outgoing = _outgoing_edges(graph, path)
    incoming = _incoming_edges(graph, path)

    if outgoing:
        lines.append("- Outgoing dependencies:")

        for edge in outgoing:
            lines.append(f"  - depends on `{edge['to']}` via `{edge['import']}`")
    else:
        lines.append("- Outgoing dependencies: none")

    if incoming:
        lines.append("- Incoming dependencies:")

        for edge in incoming:
            lines.append(f"  - used by `{edge['from']}` via `{edge['import']}`")
    else:
        lines.append("- Incoming dependencies: none")

    return lines


def _outgoing_edges(graph: dict, path: str) -> list[dict]:
    edges = []

    for edge in graph.get("edges", []):
        if edge.get("from") == path:
            edges.append(edge)

    return edges


def _incoming_edges(graph: dict, path: str) -> list[dict]:
    edges = []

    for edge in graph.get("edges", []):
        if edge.get("to") == path:
            edges.append(edge)

    return edges


def _task_words(task: str) -> list[str]:
    words = []

    for word in re.findall(r"[a-zA-Z0-9_]+", task.lower()):
        if word in TASK_WORD_STOP_WORDS:
            continue

        if len(word) <= 1:
            continue

        words.append(word)

    return _dedupe(words)


def _normalize_text(text: str) -> str:
    return text.replace("\\", "/").replace("_", " ").replace("-", " ").lower()


def _format_inline_list(values: list[str]) -> str:
    cleaned = []

    for value in values:
        if value:
            cleaned.append(str(value))

    if not cleaned:
        return "none"

    return ", ".join(f"`{value}`" for value in cleaned)


def _dedupe(values: list[str]) -> list[str]:
    seen = set()
    result = []

    for value in values:
        if value in seen:
            continue

        seen.add(value)
        result.append(value)

    return result
