import os
import re


DEFAULT_TEST_COMMANDS = [
    "py tests.py",
]


CLI_TEST_COMMANDS = [
    "py cli.py help",
    "py cli.py scan tmp_repo",
    "py cli.py show tmp_repo/main.py",
]


SYMBOL_MATCH_STOP_WORDS = {
    "add",
    "fix",
    "change",
    "update",
    "remove",
    "create",
    "make",
    "command",
    "commands",
    "test",
    "tests",
    "testing",
}


def generate_task_brief(graph: dict, task: str, max_files: int = 5) -> str:
    """Generate a Markdown task brief for an AI coding agent."""

    task = task.strip()
    files = graph.get("files", [])
    edges = graph.get("edges", [])

    scored_files = score_relevant_files(graph, task)
    relevant_files = [item["file"] for item in scored_files[:max_files]]

    if not relevant_files:
        relevant_files = files[:max_files]

    outgoing_edges = _group_edges_by_key(edges, "from")
    incoming_edges = _group_edges_by_key(edges, "to")

    lines = []

    lines.append("# Task Brief")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append("## Task")
    lines.append("")
    lines.append(task if task else "No task provided.")
    lines.append("")

    lines.append("## Relevant Files")
    lines.append("")

    if relevant_files:
        for file_info in relevant_files:
            path = file_info.get("path", "")
            reason = explain_relevance(file_info, task)
            lines.append(f"- `{path}`")
            lines.append(f"  - Why: {reason}")
    else:
        lines.append("No relevant files found.")

    lines.append("")

    lines.append("## File Context")
    lines.append("")

    for file_info in relevant_files:
        path = file_info.get("path", "")
        lines.append(f"### `{path}`")
        lines.append("")

        _add_named_items(lines, "Classes", file_info.get("classes", []))
        _add_named_items(lines, "Functions", file_info.get("functions", []))
        _add_simple_items(lines, "Imports", file_info.get("imports", []))
        _add_simple_items(lines, "External imports", file_info.get("external_imports", []))
        _add_unresolved_imports(lines, file_info.get("unresolved_import_details", []))

        file_outgoing_edges = outgoing_edges.get(path, [])
        file_incoming_edges = incoming_edges.get(path, [])

        if file_outgoing_edges:
            lines.append("- Outgoing dependencies:")

            for edge in file_outgoing_edges:
                lines.append(f"  - depends on `{edge.get('to', '')}` via `{edge.get('import', '')}`")

        if file_incoming_edges:
            lines.append("- Incoming dependencies:")

            for edge in file_incoming_edges:
                lines.append(f"  - used by `{edge.get('from', '')}` via `{edge.get('import', '')}`")

        if file_info.get("error"):
            lines.append(f"- Parse warning: `{file_info.get('error')}`")

        lines.append("")

    lines.append("## Risks")
    lines.append("")

    for risk in generate_risks(relevant_files):
        lines.append(f"- {risk}")

    lines.append("")

    lines.append("## Suggested Tests")
    lines.append("")

    for command in suggest_tests(relevant_files):
        lines.append(f"- `{command}`")

    lines.append("")

    lines.append("## Suggested Prompt for AI Agent")
    lines.append("")
    lines.append("```text")
    lines.append("You are editing the Strata repository.")
    lines.append("")
    lines.append("Task:")
    lines.append(task if task else "No task provided.")
    lines.append("")
    lines.append("Read these files first:")

    for file_info in relevant_files:
        lines.append(f"- {file_info.get('path', '')}")

    lines.append("")
    lines.append("Important constraints:")
    lines.append("- Use only the Python standard library.")
    lines.append("- Keep the implementation small and focused.")
    lines.append("- Do not touch unrelated files.")
    lines.append("- Preserve existing CLI behavior unless the task requires changing it.")
    lines.append("- Keep tests in tests.py using simple assert statements.")
    lines.append("")
    lines.append("After editing, run:")

    for command in suggest_tests(relevant_files):
        lines.append(f"- {command}")

    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def write_task_brief(graph: dict, task: str, output_path: str) -> None:
    """Write a Markdown task brief to disk."""

    output_dir = os.path.dirname(output_path)

    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    content = generate_task_brief(graph, task)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(content)


def score_relevant_files(graph: dict, task: str) -> list[dict]:
    """Return files ordered by simple task relevance score."""

    task_words = _task_words(task)
    scored_files = []

    for file_info in graph.get("files", []):
        path = file_info.get("path", "")
        filename = os.path.basename(path).lower()
        score = 0

        score += _score_file_name(filename, task_words)
        score += _score_file_purpose(filename, task_words)
        score += _score_public_symbols(file_info, task_words)
        score += _score_imports(file_info, task_words)

        scored_files.append(
            {
                "score": score,
                "file": file_info,
            }
        )

    scored_files.sort(
        key=lambda item: (
            item["score"],
            item["file"].get("path", ""),
        ),
        reverse=True,
    )

    return [item for item in scored_files if item["score"] > 0]


def explain_relevance(file_info: dict, task: str) -> str:
    filename = os.path.basename(file_info.get("path", "")).lower()
    task_words = _task_words(task)
    reasons = []

    if filename == "tests.py" and _task_mentions_any(task_words, {"test", "tests", "testing"}):
        reasons.append("the task is test-related")

    if filename == "cli.py" and _task_mentions_any(task_words, {"cli", "command", "commands", "terminal"}):
        reasons.append("this file handles Strata commands and user-facing output")

    if filename == "map_writer.py" and _task_mentions_any(task_words, {"map", "markdown", "project"}):
        reasons.append("this file generates the Markdown project map")

    if filename == "brief.py" and _task_mentions_any(task_words, {"brief", "task", "agent", "prompt", "context"}):
        reasons.append("this file generates task-specific AI context")

    if filename == "scanner.py" and _task_mentions_any(task_words, {"scan", "scanner", "graph", "import", "dependency"}):
        reasons.append("this file builds repository graph data")

    if filename == "graph.py" and _task_mentions_any(task_words, {"graph", "validate", "validation", "schema"}):
        reasons.append("this file validates graph structure and schema")

    matched_symbols = _matching_public_symbols(file_info, task_words)

    if matched_symbols:
        shown = ", ".join(f"`{name}`" for name in matched_symbols[:3])
        reasons.append(f"the task matches public symbol(s): {shown}")

    if not reasons:
        reasons.append("it matched the task relevance heuristic")

    return _dedupe_sentence_parts(reasons)


def generate_risks(relevant_files: list[dict]) -> list[str]:
    risks = []
    filenames = [os.path.basename(file_info.get("path", "")).lower() for file_info in relevant_files]

    if "cli.py" in filenames:
        risks.append("CLI behavior may change, so command output should be checked manually.")

    if "scanner.py" in filenames:
        risks.append("Graph generation may change, so import edges and unresolved imports should be verified.")

    if "graph.py" in filenames:
        risks.append("Graph schema validation may reject valid data if checks become too strict.")

    if "tests.py" in filenames:
        risks.append("Tests should check important behavior without depending too much on exact formatting.")

    if "map_writer.py" in filenames:
        risks.append("Markdown output should stay readable for both humans and AI agents.")

    if "brief.py" in filenames:
        risks.append("Task relevance may be imperfect because this version uses simple heuristics.")

    if not risks:
        risks.append("The change may affect files not selected by the simple relevance heuristic.")

    return risks


def suggest_tests(relevant_files: list[dict]) -> list[str]:
    commands = list(DEFAULT_TEST_COMMANDS)
    filenames = [os.path.basename(file_info.get("path", "")).lower() for file_info in relevant_files]

    if "cli.py" in filenames:
        commands.extend(CLI_TEST_COMMANDS)

    if "map_writer.py" in filenames:
        commands.append("py cli.py map tmp_repo")

    if "brief.py" in filenames:
        commands.append('py cli.py brief "add map command tests"')

    return _dedupe_list(commands)


def _score_file_name(filename: str, task_words: set[str]) -> int:
    score = 0
    file_stem = filename.replace(".py", "")

    for word in task_words:
        if word == file_stem:
            score += 10
        elif word in file_stem:
            score += 4

    return score


def _score_file_purpose(filename: str, task_words: set[str]) -> int:
    score = 0

    if filename == "tests.py" and _task_mentions_any(task_words, {"test", "tests", "testing"}):
        score += 20

    if filename == "cli.py" and _task_mentions_any(task_words, {"cli", "command", "commands", "terminal"}):
        score += 18

    if filename == "map_writer.py" and _task_mentions_any(task_words, {"map", "markdown", "project"}):
        score += 18

    if filename == "brief.py" and _task_mentions_any(task_words, {"brief", "task", "agent", "prompt", "context"}):
        score += 18

    if filename == "scanner.py" and _task_mentions_any(task_words, {"scan", "scanner", "import", "dependency"}):
        score += 16

    if filename == "graph.py" and _task_mentions_any(task_words, {"graph", "validate", "validation", "schema"}):
        score += 16

    return score


def _score_public_symbols(file_info: dict, task_words: set[str]) -> int:
    score = 0
    useful_task_words = task_words - SYMBOL_MATCH_STOP_WORDS

    for function in file_info.get("functions", []):
        name = function.get("name", "")

        if name.startswith("_"):
            continue

        name_lower = name.lower()

        for word in useful_task_words:
            if word in name_lower:
                score += 3

    for class_info in file_info.get("classes", []):
        name = class_info.get("name", "")
        name_lower = name.lower()

        for word in useful_task_words:
            if word in name_lower:
                score += 4

    return score


def _score_imports(file_info: dict, task_words: set[str]) -> int:
    score = 0

    for import_name in file_info.get("imports", []):
        import_lower = import_name.lower()

        for word in task_words:
            if word == import_lower:
                score += 2

    return score


def _matching_public_symbols(file_info: dict, task_words: set[str]) -> list[str]:
    matches = []
    useful_task_words = task_words - SYMBOL_MATCH_STOP_WORDS

    for function in file_info.get("functions", []):
        name = function.get("name", "")

        if name.startswith("_"):
            continue

        name_lower = name.lower()

        for word in useful_task_words:
            if word in name_lower:
                matches.append(name)
                break

    for class_info in file_info.get("classes", []):
        name = class_info.get("name", "")
        name_lower = name.lower()

        for word in useful_task_words:
            if word in name_lower:
                matches.append(name)
                break

    return _dedupe_list(matches)


def _task_words(task: str) -> set[str]:
    words = set()

    for word in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", task.lower()):
        if len(word) >= 3:
            words.add(word)

    return words


def _task_mentions_any(task_words: set[str], candidates: set[str]) -> bool:
    return bool(task_words.intersection(candidates))


def _group_edges_by_key(edges: list[dict], key: str) -> dict:
    grouped = {}

    for edge in edges:
        value = edge.get(key)

        if not value:
            continue

        grouped.setdefault(value, []).append(edge)

    return grouped


def _add_named_items(lines: list[str], label: str, items: list[dict]) -> None:
    if not items:
        return

    names = []

    for item in items:
        name = item.get("name")

        if name:
            names.append(name)

    if names:
        lines.append(f"- {label}: {', '.join(f'`{name}`' for name in names)}")


def _add_simple_items(lines: list[str], label: str, items: list[str]) -> None:
    if not items:
        return

    lines.append(f"- {label}: {', '.join(f'`{item}`' for item in items)}")


def _add_unresolved_imports(lines: list[str], items: list[dict]) -> None:
    if not items:
        return

    formatted_items = []

    for item in items:
        name = item.get("name", "")
        line = item.get("line", "")
        formatted_items.append(f"`{name}` at line `{line}`")

    if formatted_items:
        lines.append(f"- Unresolved imports: {', '.join(formatted_items)}")


def _dedupe_list(items: list[str]) -> list[str]:
    result = []

    for item in items:
        if item not in result:
            result.append(item)

    return result


def _dedupe_sentence_parts(items: list[str]) -> str:
    return "; ".join(_dedupe_list(items)) + "."