from cli_ui import bold, cyan, dim


def print_usage() -> None:
    print(bold("Strata"))
    print(dim("Local-first repository intelligence for AI coding agents."))
    print()

    print(bold("Usage:"))
    print("  strata scan [path]")
    print("  strata show [path]")
    print("  strata map [path]")
    print("  strata routes [path]")
    print("  strata diff [path]")
    print("  strata snapshot [path]")
    print("  strata verify")
    print("  strata verify <root>")
    print("  strata gate")
    print("  strata gate <root>")
    print("  strata review")
    print("  strata review <root>")
    print("  strata config [root]")
    print("  strata config init [root]")
    print("  strata config set <key> <value> [root]")
    print("  strata config set mode hybrid")
    print("  strata config set agent codex")
    print("  strata config set auto_snapshot false")
    print('  strata brief "<task>"')
    print('  strata brief <path> "<task>"')
    print("  strata cycles [path]")
    print("  strata health [path]")
    print("  strata impact <file>")
    print("  strata impact <root> <file>")
    print("  strata tests-for <file>")
    print("  strata tests-for <root> <file>")
    print('  strata preflight "<task>"')
    print('  strata preflight <root> "<task>"')
    print('  strata context "<task>"')
    print('  strata context <root> "<task>"')
    print('  strata prepare "<task>"')
    print('  strata prepare "<task>" <root>')
    print('  strata agent-prompt "<task>" <agent>')
    print('  strata agent-prompt <root> "<task>" <agent>')
    print("  strata status [path]")
    print("  strata help")
    print()

    print(dim("Legacy fallback: use `py cli.py ...` if the `strata` entry point is unavailable."))
    print()

    print(bold("Commands:"))
    print(f"  {cyan('scan')}          Build .aidc/graph.json")
    print(f"  {cyan('show')}          Show saved graph summary or one file")
    print(f"  {cyan('map')}           Generate .aidc/project_map.md")
    print(f"  {cyan('routes')}        Generate .aidc/routes.md and .aidc/routes.json")
    print(f"  {cyan('diff')}          Compare the latest snapshot against the current repository structure.")
    print(f"  {cyan('snapshot')}      Save a timestamped structural snapshot for later diff/verify.")
    print(f"  {cyan('verify')}        Verify current repository structure against the latest snapshot.")
    print(f"  {cyan('gate')}          Check current repository readiness without requiring a snapshot.")
    print(f"  {cyan('review')}        Run diff, optional verify, and gate in one post-edit review.")
    print(f"  {cyan('config')}        Show or initialize .aidc/config.json")
    print(f"  {cyan('config set')}    Update a workflow config value")
    print(f"  {cyan('brief')}         Generate .aidc/task_brief.md")
    print(f"  {cyan('cycles')}        Check circular dependencies")
    print(f"  {cyan('health')}        Show dependency health summary")
    print(f"  {cyan('impact')}        Analyze impact of changing a file")
    print(f"  {cyan('tests-for')}     Suggest tests for a changed file")
    print(f"  {cyan('preflight')}     Generate .aidc/preflight.md")
    print(f"  {cyan('context')}       Generate a compact deterministic AI context pack for a task.")
    print(f"  {cyan('prepare')}       Run scan, context, preflight, and agent prompt generation.")
    print(f"  {cyan('agent-prompt')}  Generate .aidc/agent_prompt.md")
    print(f"  {cyan('status')}        Check generated Strata output status")
    print(f"  {cyan('help')}          Show this help message")
    print()

    print(bold("Supported agents:"))
    print("  generic, local, aider, chatgpt")
