from cli_ui import bold, cyan, dim


def print_usage() -> None:
    print(bold("Strata"))
    print(dim("Local-first repository intelligence for AI coding agents."))
    print()

    print(bold("Usage:"))
    print("  py cli.py scan [path]")
    print("  py cli.py show [path]")
    print("  py cli.py map [path]")
    print("  py cli.py routes [path]")
    print("  py cli.py diff [path]")
    print("  py cli.py snapshot [path]")
    print("  py cli.py verify")
    print("  py cli.py verify <root>")
    print("  py cli.py gate")
    print("  py cli.py gate <root>")
    print('  py cli.py brief "<task>"')
    print('  py cli.py brief <path> "<task>"')
    print("  py cli.py cycles [path]")
    print("  py cli.py health [path]")
    print("  py cli.py impact <file>")
    print("  py cli.py impact <root> <file>")
    print("  py cli.py tests-for <file>")
    print("  py cli.py tests-for <root> <file>")
    print('  py cli.py preflight "<task>"')
    print('  py cli.py preflight <root> "<task>"')
    print('  py cli.py context "<task>"')
    print('  py cli.py context <root> "<task>"')
    print('  py cli.py agent-prompt "<task>" <agent>')
    print('  py cli.py agent-prompt <root> "<task>" <agent>')
    print("  py cli.py status [path]")
    print("  py cli.py help")
    print()

    print(bold("Commands:"))
    print(f"  {cyan('scan')}          Build .aidc/graph.json")
    print(f"  {cyan('show')}          Show saved graph summary or one file")
    print(f"  {cyan('map')}           Generate .aidc/project_map.md")
    print(f"  {cyan('routes')}        Generate .aidc/routes.md and .aidc/routes.json")
    print(f"  {cyan('diff')}          Compare the latest snapshot against the current repository structure.")
    print(f"  {cyan('snapshot')}      Save a timestamped structural snapshot for later diff/verify.")
    print(f"  {cyan('verify')}        Verify current repository structure against the latest snapshot.")
    print(f"  {cyan('gate')}          Check current repository readiness without requiring a snapshot.")
    print(f"  {cyan('brief')}         Generate .aidc/task_brief.md")
    print(f"  {cyan('cycles')}        Check circular dependencies")
    print(f"  {cyan('health')}        Show dependency health summary")
    print(f"  {cyan('impact')}        Analyze impact of changing a file")
    print(f"  {cyan('tests-for')}     Suggest tests for a changed file")
    print(f"  {cyan('preflight')}     Generate .aidc/preflight.md")
    print(f"  {cyan('context')}       Generate a compact deterministic AI context pack for a task.")
    print(f"  {cyan('agent-prompt')}  Generate .aidc/agent_prompt.md")
    print(f"  {cyan('status')}        Check generated Strata output status")
    print(f"  {cyan('help')}          Show this help message")
    print()

    print(bold("Supported agents:"))
    print("  generic, local, aider, chatgpt")
