import os


def generate_project_map(graph: dict) -> str:
    """Generate a Markdown project map from a Strata graph."""

    files = graph.get("files", [])
    edges = graph.get("edges", [])

    outgoing_edges = _group_edges_by_key(edges, "from")
    incoming_edges = _group_edges_by_key(edges, "to")

    lines = []

    lines.append("# Project Map")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Project root: `{graph.get('root', '')}`")
    lines.append(f"- Schema version: `{graph.get('schema_version', '')}`")
    lines.append(f"- Files: `{len(files)}`")
    lines.append(f"- Dependency edges: `{len(edges)}`")
    lines.append("")

    lines.append("## Files")
    lines.append("")

    if not files:
        lines.append("No files found.")
        lines.append("")
        return "\n".join(lines)

    for file_info in sorted(files, key=lambda item: item.get("path", "")):
        path = file_info.get("path", "")
        lines.append(f"### `{path}`")
        lines.append("")

        language = file_info.get("language")
        if language:
            lines.append(f"- Language: `{language}`")

        _add_named_items(lines, "Classes", file_info.get("classes", []))
        _add_named_items(lines, "Functions", file_info.get("functions", []))
        _add_simple_items(lines, "Imports", file_info.get("imports", []))
        _add_simple_items(lines, "External imports", file_info.get("external_imports", []))
        _add_unresolved_imports(lines, file_info.get("unresolved_import_details", []))

        if file_info.get("error"):
            lines.append(f"- Parse warning: `{file_info.get('error')}`")

        _add_dependency_section(
            lines,
            "Outgoing dependencies",
            outgoing_edges.get(path, []),
            direction="outgoing",
        )

        _add_dependency_section(
            lines,
            "Incoming dependencies",
            incoming_edges.get(path, []),
            direction="incoming",
        )

        lines.append("")

    lines.append("## Warnings")
    lines.append("")

    warning_count = 0

    for file_info in sorted(files, key=lambda item: item.get("path", "")):
        path = file_info.get("path", "")
        unresolved = file_info.get("unresolved_import_details", [])

        for item in unresolved:
            name = item.get("name", "")
            line = item.get("line", "")
            lines.append(f"- `{path}` has unresolved import `{name}` at line `{line}`")
            warning_count += 1

        if file_info.get("error"):
            lines.append(f"- `{path}` has parse warning: `{file_info.get('error')}`")
            warning_count += 1

    if warning_count == 0:
        lines.append("No warnings found.")

    lines.append("")

    return "\n".join(lines)


def write_project_map(graph: dict, output_path: str) -> None:
    """Write a Markdown project map to disk."""

    output_dir = os.path.dirname(output_path)

    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    content = generate_project_map(graph)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(content)


def _group_edges_by_key(edges: list[dict], key: str) -> dict:
    grouped = {}

    for edge in edges:
        value = edge.get(key)

        if not value:
            continue

        grouped.setdefault(value, []).append(edge)

    return grouped


def _add_named_items(lines: list[str], label: str, items: list[dict]) -> None:
    if not items:
        return

    names = []

    for item in items:
        name = item.get("name")

        if name:
            names.append(name)

    if names:
        lines.append(f"- {label}: {', '.join(f'`{name}`' for name in names)}")


def _add_simple_items(lines: list[str], label: str, items: list[str]) -> None:
    if not items:
        return

    lines.append(f"- {label}: {', '.join(f'`{item}`' for item in items)}")


def _add_unresolved_imports(lines: list[str], items: list[dict]) -> None:
    if not items:
        return

    formatted_items = []

    for item in items:
        name = item.get("name", "")
        line = item.get("line", "")
        formatted_items.append(f"`{name}` at line `{line}`")

    if formatted_items:
        lines.append(f"- Unresolved imports: {', '.join(formatted_items)}")


def _add_dependency_section(
    lines: list[str],
    label: str,
    edges: list[dict],
    direction: str,
) -> None:
    if not edges:
        return

    lines.append(f"- {label}:")

    for edge in sorted(edges, key=lambda item: (item.get("to", ""), item.get("from", ""))):
        import_name = edge.get("import", "")

        if direction == "outgoing":
            target = edge.get("to", "")
            lines.append(f"  - depends on `{target}` via `{import_name}`")
        else:
            source = edge.get("from", "")
            lines.append(f"  - used by `{source}` via `{import_name}`")