import os

from secret_redaction import redact_text
from brief import explain_relevance, score_relevant_files
from brief_impact import generate_impact_notes
from health import analyze_health
from test_mapper import suggest_tests_for_file


def generate_preflight_report(graph: dict, task: str, max_files: int = 5) -> str:
    """Generate a consolidated pre-edit report for a task."""

    task = redact_text(task)
    scored_files = score_relevant_files(graph, task)
    relevant_files = scored_files[:max_files]
    grouped_files = _group_relevant_files(relevant_files)
    health = analyze_health(graph)
    verification = _generate_verification_plan(graph, relevant_files)

    lines = []

    lines.append("# Preflight Report")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append("## Task")
    lines.append("")
    lines.append(task)
    lines.append("")
    lines.append("## Repository Summary")
    lines.append("")
    lines.append(f"- Project root: `{graph.get('root', '')}`")
    lines.append(f"- Schema version: `{graph.get('schema_version', '')}`")
    lines.append(f"- Files scanned: `{len(graph.get('files', []))}`")
    lines.append(f"- Dependency edges: `{len(graph.get('edges', []))}`")
    lines.append(f"- Backend routes: `{_count_routes(graph.get('files', []))}`")
    lines.append("")
    lines.append("## Repository Health")
    lines.append("")
    lines.append(f"- Status: `{health.get('status', 'unknown')}`")
    lines.append(f"- Unresolved imports: `{health.get('unresolved_import_count', 0)}`")
    lines.append(f"- Circular dependencies: `{health.get('cycle_count', 0)}`")

    if health.get("unresolved_imports"):
        lines.append("")
        lines.append("Unresolved import details:")

        for item in health["unresolved_imports"]:
            lines.append(
                f"- `{item.get('path', '')}` imports "
                f"`{item.get('name', '')}` at line `{item.get('line', '')}`"
            )

    if health.get("cycles"):
        lines.append("")
        lines.append("Circular dependency details:")

        for cycle in health["cycles"]:
            lines.append(f"- {' -> '.join(f'`{path}`' for path in cycle)}")

    lines.append("")
    _add_backend_routes_section(lines, graph.get("files", []))
    lines.append("")
    lines.extend(_format_grouped_relevant_files(graph, task, grouped_files))
    lines.append("")
    lines.append(generate_impact_notes(graph, relevant_files))
    lines.append("")
    lines.append("## Verification Plan")
    lines.append("")
    lines.append("Recommended commands:")

    for command in verification["commands"]:
        lines.append(f"- `{command}`")

    lines.append("")
    lines.append("Likely related test files:")

    if verification["test_files"]:
        for path in verification["test_files"]:
            lines.append(f"- `{path}`")
    else:
        lines.append("- none")

    lines.append("")
    lines.append("## AI Agent Instructions")
    lines.append("")
    lines.append("Use this with an AI coding assistant before editing:")
    lines.append("")
    lines.append("```text")
    lines.append(f"Task: {task}")
    lines.append("")

    routes = _all_routes(graph.get("files", []))

    if routes:
        lines.append("Backend routes detected:")
        for route in routes:
            method = route.get("method", "")
            route_path = route.get("path", "")
            file_path = route.get("file", "")
            line = route.get("line", "")
            lines.append(f"- {method} {route_path} -> {file_path}:{line}")
        lines.append("")

    lines.append("Read these files first:")

    if relevant_files:
        for item in relevant_files:
            lines.append(f"- {item['file'].get('path', '')}")
    else:
        lines.append("- No specific files selected. Inspect the project map first.")

    lines.append("")
    lines.append("Before editing:")
    lines.append("- Review repository health warnings.")
    lines.append("- Review backend routes if this task touches API behavior.")
    lines.append("- Review relevant source files before test files.")
    lines.append("- Review impact notes for each relevant file.")
    lines.append("- Prefer the smallest safe change.")
    lines.append("- Do not edit unrelated files.")
    lines.append("- Use only the Python standard library.")
    lines.append("")
    lines.append("After editing, run:")

    for command in verification["commands"]:
        lines.append(f"- {command}")

    lines.append("```")

    return redact_text("\n".join(lines).rstrip() + "\n")


def write_preflight_report(graph: dict, task: str, output_path: str) -> None:
    """Write a preflight report to disk."""

    directory = os.path.dirname(output_path)

    if directory:
        os.makedirs(directory, exist_ok=True)

    content = generate_preflight_report(graph, task)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(redact_text(content))


def _format_grouped_relevant_files(
    graph: dict,
    task: str,
    grouped_files: dict[str, list[dict]],
) -> list[str]:
    lines = []

    lines.append("## Relevant Source Files")
    lines.append("")

    if grouped_files["source"]:
        lines.extend(_format_relevant_file_group(graph, task, grouped_files["source"]))
    else:
        lines.append("No strongly relevant source files found.")

    lines.append("")
    lines.append("## Relevant Test Files")
    lines.append("")

    if grouped_files["tests"]:
        lines.extend(_format_relevant_file_group(graph, task, grouped_files["tests"]))
    else:
        lines.append("No strongly relevant test files found.")

    lines.append("")
    lines.append("## Entry Points / Runners")
    lines.append("")

    if grouped_files["entrypoints"]:
        lines.extend(_format_relevant_file_group(graph, task, grouped_files["entrypoints"]))
    else:
        lines.append("No relevant entry points or runners found.")

    return lines


def _format_relevant_file_group(graph: dict, task: str, files: list[dict]) -> list[str]:
    lines = []

    for index, item in enumerate(files, start=1):
        file_info = item["file"]
        score = item["score"]
        reason = explain_relevance(file_info, task)

        lines.append(f"{index}. `{file_info.get('path', '')}`")
        lines.append(f"   - Relevance score: `{score}`")
        lines.append(f"   - Reason: {reason}")

    return lines


def _group_relevant_files(relevant_files: list[dict]) -> dict[str, list[dict]]:
    groups = {
        "source": [],
        "tests": [],
        "entrypoints": [],
    }

    for item in relevant_files:
        file_info = item.get("file", {})
        path = file_info.get("path", "")
        normalized_path = _normalize_path(path)
        basename = os.path.basename(normalized_path)

        if _is_entrypoint_file(normalized_path, basename):
            groups["entrypoints"].append(item)
        elif _is_test_file(normalized_path, basename):
            groups["tests"].append(item)
        else:
            groups["source"].append(item)

    return groups


def _generate_verification_plan(graph: dict, relevant_files: list[dict]) -> dict:
    commands = ["py tests.py"]
    test_files = []

    for item in relevant_files:
        file_info = item.get("file", {})
        path = file_info.get("path", "")

        if not path:
            continue

        suggestion = suggest_tests_for_file(graph, path)

        for command in suggestion.get("recommended_commands", []):
            commands.append(command)

        for test_file in suggestion.get("related_test_files", []):
            test_files.append(test_file)

    return {
        "commands": _dedupe(commands),
        "test_files": _dedupe(test_files),
    }


def _count_routes(files: list[dict]) -> int:
    count = 0

    for file_info in files:
        count += len(file_info.get("routes", []))

    return count


def _all_routes(files: list[dict]) -> list[dict]:
    routes = []

    for file_info in files:
        path = file_info.get("path", "")

        for route in file_info.get("routes", []):
            routes.append(
                {
                    "file": path,
                    "method": route.get("method", ""),
                    "path": route.get("path", ""),
                    "line": route.get("line", ""),
                    "source": route.get("source", ""),
                }
            )

    return sorted(
        routes,
        key=lambda item: (
            item.get("file", ""),
            str(item.get("line", "")),
            item.get("method", ""),
            item.get("path", ""),
        ),
    )


def _add_backend_routes_section(lines: list[str], files: list[dict]) -> None:
    routes = _all_routes(files)

    if not routes:
        return

    lines.append("## Backend Routes")
    lines.append("")
    lines.append("| Method | Route | File | Source |")
    lines.append("| --- | --- | --- | --- |")

    for route in routes:
        method = route.get("method", "")
        route_path = route.get("path", "")
        file_path = route.get("file", "")
        line = route.get("line", "")
        source = route.get("source", "")

        lines.append(
            f"| `{method}` | `{route_path}` | `{file_path}:{line}` | `{source}` |"
        )


def _is_test_file(normalized_path: str, basename: str) -> bool:
    if normalized_path.startswith("tests/") and basename.startswith("test_"):
        return True

    return False


def _is_entrypoint_file(normalized_path: str, basename: str) -> bool:
    if basename == "tests.py":
        return True

    if basename == "cli.py":
        return True

    return False


def _normalize_path(path: str) -> str:
    return path.replace("\\", "/").strip()


def _dedupe(values: list[str]) -> list[str]:
    seen = set()
    result = []

    for value in values:
        if value in seen:
            continue

        seen.add(value)
        result.append(value)

    return result
