import os

from brief import explain_relevance, score_relevant_files
from brief_impact import generate_impact_notes
from health import analyze_health
from test_mapper import suggest_tests_for_file


def generate_preflight_report(graph: dict, task: str, max_files: int = 5) -> str:
    """Generate a consolidated pre-edit report for a task."""

    scored_files = score_relevant_files(graph, task)
    relevant_files = scored_files[:max_files]
    health = analyze_health(graph)
    verification = _generate_verification_plan(graph, relevant_files)

    lines = []

    lines.append("# Preflight Report")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append("## Task")
    lines.append("")
    lines.append(task)
    lines.append("")
    lines.append("## Repository Summary")
    lines.append("")
    lines.append(f"- Project root: `{graph.get('root', '')}`")
    lines.append(f"- Schema version: `{graph.get('schema_version', '')}`")
    lines.append(f"- Files scanned: `{len(graph.get('files', []))}`")
    lines.append(f"- Dependency edges: `{len(graph.get('edges', []))}`")
    lines.append("")
    lines.append("## Repository Health")
    lines.append("")
    lines.append(f"- Status: `{health.get('status', 'unknown')}`")
    lines.append(f"- Unresolved imports: `{health.get('unresolved_import_count', 0)}`")
    lines.append(f"- Circular dependencies: `{health.get('cycle_count', 0)}`")

    if health.get("unresolved_imports"):
        lines.append("")
        lines.append("Unresolved import details:")

        for item in health["unresolved_imports"]:
            lines.append(
                f"- `{item.get('path', '')}` imports "
                f"`{item.get('name', '')}` at line `{item.get('line', '')}`"
            )

    if health.get("cycles"):
        lines.append("")
        lines.append("Circular dependency details:")

        for cycle in health["cycles"]:
            lines.append(f"- {' -> '.join(f'`{path}`' for path in cycle)}")

    lines.append("")
    lines.append("## Relevant Files")
    lines.append("")

    if relevant_files:
        for index, item in enumerate(relevant_files, start=1):
            file_info = item["file"]
            score = item["score"]
            reason = explain_relevance(file_info, task)

            lines.append(f"{index}. `{file_info.get('path', '')}`")
            lines.append(f"   - Relevance score: `{score}`")
            lines.append(f"   - Reason: {reason}")
    else:
        lines.append("No strongly relevant files found.")

    lines.append("")
    lines.append(generate_impact_notes(graph, relevant_files))
    lines.append("")
    lines.append("## Verification Plan")
    lines.append("")
    lines.append("Recommended commands:")

    for command in verification["commands"]:
        lines.append(f"- `{command}`")

    lines.append("")
    lines.append("Likely related test files:")

    if verification["test_files"]:
        for path in verification["test_files"]:
            lines.append(f"- `{path}`")
    else:
        lines.append("- none")

    lines.append("")
    lines.append("## AI Agent Instructions")
    lines.append("")
    lines.append("Use this with an AI coding assistant before editing:")
    lines.append("")
    lines.append("```text")
    lines.append(f"Task: {task}")
    lines.append("")
    lines.append("Read these files first:")

    if relevant_files:
        for item in relevant_files:
            lines.append(f"- {item['file'].get('path', '')}")
    else:
        lines.append("- No specific files selected. Inspect the project map first.")

    lines.append("")
    lines.append("Before editing:")
    lines.append("- Review repository health warnings.")
    lines.append("- Review impact notes for each relevant file.")
    lines.append("- Prefer the smallest safe change.")
    lines.append("- Do not edit unrelated files.")
    lines.append("- Use only the Python standard library.")
    lines.append("")
    lines.append("After editing, run:")
    for command in verification["commands"]:
        lines.append(f"- {command}")
    lines.append("```")

    return "\n".join(lines).rstrip() + "\n"


def write_preflight_report(graph: dict, task: str, output_path: str) -> None:
    """Write a preflight report to disk."""

    directory = os.path.dirname(output_path)

    if directory:
        os.makedirs(directory, exist_ok=True)

    content = generate_preflight_report(graph, task)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(content)


def _generate_verification_plan(graph: dict, relevant_files: list[dict]) -> dict:
    commands = ["py tests.py"]
    test_files = []

    for item in relevant_files:
        file_info = item.get("file", {})
        path = file_info.get("path", "")

        if not path:
            continue

        suggestion = suggest_tests_for_file(graph, path)

        for command in suggestion.get("recommended_commands", []):
            commands.append(command)

        for test_file in suggestion.get("related_test_files", []):
            test_files.append(test_file)

    return {
        "commands": _dedupe(commands),
        "test_files": _dedupe(test_files),
    }


def _dedupe(values: list[str]) -> list[str]:
    seen = set()
    result = []

    for value in values:
        if value in seen:
            continue

        seen.add(value)
        result.append(value)

    return result