import json
import os


def collect_routes(graph: dict) -> list[dict]:
    """Collect backend routes from all parsed files in a graph."""

    collected_routes = []

    for file_info in graph.get("files", []):
        file_path = file_info.get("path", "")

        for route in file_info.get("routes", []):
            collected_routes.append(
                {
                    "method": route.get("method", ""),
                    "path": route.get("path", ""),
                    "file": file_path,
                    "line": route.get("line", ""),
                    "source": route.get("source", ""),
                    "language": file_info.get("language", ""),
                    "framework": file_info.get("framework", ""),
                }
            )

    return sorted(
        collected_routes,
        key=lambda item: (
            item.get("path", ""),
            item.get("method", ""),
            item.get("file", ""),
            str(item.get("line", "")),
        ),
    )


def find_duplicate_routes(routes: list[dict]) -> list[dict]:
    """Find routes with the same HTTP method and path in multiple places."""

    grouped = {}

    for route in routes:
        key = (
            route.get("method", ""),
            route.get("path", ""),
        )
        grouped.setdefault(key, []).append(route)

    duplicates = []

    for key, items in grouped.items():
        if len(items) <= 1:
            continue

        method, route_path = key

        duplicates.append(
            {
                "method": method,
                "path": route_path,
                "locations": items,
            }
        )

    return sorted(
        duplicates,
        key=lambda item: (
            item.get("path", ""),
            item.get("method", ""),
        ),
    )


def route_files_with_unresolved_imports(graph: dict) -> list[dict]:
    """Find files that contain routes and also have unresolved imports."""

    risky_files = []

    for file_info in graph.get("files", []):
        routes = file_info.get("routes", [])
        unresolved = file_info.get("unresolved_import_details", [])

        if not routes or not unresolved:
            continue

        risky_files.append(
            {
                "file": file_info.get("path", ""),
                "routes": routes,
                "unresolved_imports": unresolved,
            }
        )

    return sorted(risky_files, key=lambda item: item.get("file", ""))


def generate_routes_report(graph: dict) -> str:
    """Generate a Markdown backend route map report."""

    routes = collect_routes(graph)
    duplicates = find_duplicate_routes(routes)
    route_import_risks = route_files_with_unresolved_imports(graph)

    lines = []

    lines.append("# Route Map")
    lines.append("")
    lines.append("Generated by Strata.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Project root: `{graph.get('root', '')}`")
    lines.append(f"- Files scanned: `{len(graph.get('files', []))}`")
    lines.append(f"- Backend routes: `{len(routes)}`")
    lines.append(f"- Duplicate route warnings: `{len(duplicates)}`")
    lines.append(f"- Route files with unresolved imports: `{len(route_import_risks)}`")
    lines.append("")

    lines.append("## Routes")
    lines.append("")

    if not routes:
        lines.append("No backend routes found.")
        lines.append("")
    else:
        lines.append("| Method | Route | File | Source | Language |")
        lines.append("| --- | --- | --- | --- | --- |")

        for route in routes:
            method = route.get("method", "")
            route_path = route.get("path", "")
            file_path = route.get("file", "")
            line = route.get("line", "")
            source = route.get("source", "")
            language = route.get("language", "")

            lines.append(
                f"| `{method}` | `{route_path}` | `{file_path}:{line}` | "
                f"`{source}` | `{language}` |"
            )

        lines.append("")

    lines.append("## Duplicate Route Warnings")
    lines.append("")

    if not duplicates:
        lines.append("No duplicate routes found.")
        lines.append("")
    else:
        for duplicate in duplicates:
            method = duplicate.get("method", "")
            route_path = duplicate.get("path", "")

            lines.append(f"- Duplicate route `{method} {route_path}` found in:")

            for location in duplicate.get("locations", []):
                file_path = location.get("file", "")
                line = location.get("line", "")
                source = location.get("source", "")
                lines.append(f"  - `{file_path}:{line}` via `{source}`")

            lines.append("")

    lines.append("## Route Import Risks")
    lines.append("")

    if not route_import_risks:
        lines.append("No route files with unresolved imports found.")
        lines.append("")
    else:
        for item in route_import_risks:
            file_path = item.get("file", "")
            lines.append(f"- `{file_path}` contains routes and unresolved imports:")

            for unresolved in item.get("unresolved_imports", []):
                name = unresolved.get("name", "")
                line = unresolved.get("line", "")
                lines.append(f"  - `{name}` at line `{line}`")

            lines.append("")

    lines.append("## AI Notes")
    lines.append("")
    lines.append("- Review duplicate route warnings before editing API behavior.")
    lines.append("- Review route files with unresolved imports before changing backend logic.")
    lines.append("- Use this route map with `preflight` when asking an AI assistant to edit API code.")
    lines.append("")

    return "\n".join(lines)


def write_routes_report(graph: dict, output_path: str) -> None:
    """Write the Markdown route map report to disk."""

    output_dir = os.path.dirname(output_path)

    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    content = generate_routes_report(graph)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(content)


def write_routes_json(graph: dict, output_path: str) -> None:
    """Write collected route data to JSON."""

    output_dir = os.path.dirname(output_path)

    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    routes = collect_routes(graph)
    duplicates = find_duplicate_routes(routes)
    route_import_risks = route_files_with_unresolved_imports(graph)

    payload = {
        "root": graph.get("root", ""),
        "route_count": len(routes),
        "routes": routes,
        "duplicate_routes": duplicates,
        "route_import_risks": route_import_risks,
    }

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2)