import os

from brief import generate_task_brief, score_relevant_files
from cli import write_brief
from scanner import scan_repo
from tests.helpers import run_silently


def test_task_brief_generation_includes_main_sections():
    graph = scan_repo(".")
    content = generate_task_brief(graph, "add map command tests")

    assert "# Task Brief" in content
    assert "Generated by Strata." in content
    assert "## Task" in content
    assert "add map command tests" in content
    assert "## Relevant Files" in content
    assert "## File Context" in content
    assert "## Impact Notes" in content
    assert "## Risks" in content
    assert "## Suggested Tests" in content
    assert "## Suggested Prompt for AI Agent" in content


def test_task_brief_relevance_for_map_command_tests_is_focused():
    graph = scan_repo(".")
    scored_files = score_relevant_files(graph, "add map command tests")

    selected_paths = [
        item["file"]["path"].replace("\\", "/")
        for item in scored_files[:3]
    ]

    selected_filenames = [
        os.path.basename(path)
        for path in selected_paths
    ]

    assert any(path.endswith("tests/test_map_writer.py") for path in selected_paths)
    assert "map_writer.py" in selected_filenames
    assert "cli.py" in selected_filenames
    assert "brief.py" not in selected_filenames


def test_task_brief_generation_includes_prompt_and_tests():
    graph = scan_repo(".")
    content = generate_task_brief(graph, "add map command tests")

    assert "Read these files first:" in content
    assert "tests/test_map_writer.py" in content or "tests\\test_map_writer.py" in content
    assert "- map_writer.py" in content
    assert "- cli.py" in content

    assert "py tests.py" in content
    assert "py cli.py help" in content
    assert "py cli.py map tmp_repo" in content

    assert "Use only the Python standard library." in content
    assert "Do not touch unrelated files." in content


def test_cli_write_brief_creates_task_brief_file():
    exit_code = run_silently(write_brief, ".", "add map command tests")

    assert exit_code == 0
    assert os.path.exists(".aidc/graph.json")
    assert os.path.exists(".aidc/task_brief.md")

    with open(".aidc/task_brief.md", "r", encoding="utf-8") as file:
        content = file.read()

    assert "# Task Brief" in content
    assert "add map command tests" in content
    assert "tests/test_map_writer.py" in content or "tests\\test_map_writer.py" in content
    assert "map_writer.py" in content
    assert "cli.py" in content
    assert "## Impact Notes" in content
    assert "Suggested Prompt for AI Agent" in content


TESTS = [
    test_task_brief_generation_includes_main_sections,
    test_task_brief_relevance_for_map_command_tests_is_focused,
    test_task_brief_generation_includes_prompt_and_tests,
    test_cli_write_brief_creates_task_brief_file,
]