import contextlib
import os
import tempfile
from pathlib import Path

import map_writer as old_map_writer
import strata.core.map_writer as new_map_writer
import commands.map_command as old_map_command
import strata.commands.map_command as new_map_command
from cli import write_map
from map_writer import generate_project_map
from scanner import scan_repo
from tests.helpers import capture_output


@contextlib.contextmanager
def change_directory(path: Path):
    original = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(original)


def test_new_map_command_import_matches_legacy_shim():
    assert new_map_command.write_map is old_map_command.write_map


def _create_map_repo(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)

    (root / "helper.py").write_text(
        "class App:\n"
        "    pass\n\n"
        "def help_user():\n"
        "    return True\n",
        encoding="utf-8",
    )
    (root / "main.py").write_text(
        "import os\n"
        "import helper\n"
        "import missing_module\n\n"
        "def run():\n"
        "    return helper.help_user()\n",
        encoding="utf-8",
    )


def test_map_writer_core_import_matches_compatibility_shim():
    assert old_map_writer.generate_project_map is new_map_writer.generate_project_map


def test_project_map_generation_includes_repo_summary():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert "# Project Map" in content
        assert "Generated by Strata." in content
        assert f"Project root: `{root}`" in content
        assert "Schema version: `1`" in content
        assert "Files: `2`" in content
        assert "Dependency edges: `1`" in content


def test_project_map_generation_includes_files_symbols_and_imports():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert str(root / "helper.py") in content
        assert str(root / "main.py") in content

        assert "Functions: `help_user`" in content
        assert "Functions: `run`" in content
        assert "Classes: `App`" in content

        assert "Imports: `os`, `helper`, `missing_module`" in content
        assert "External imports: `os`" in content
        assert "Unresolved imports: `missing_module` at line `3`" in content


def test_project_map_generation_includes_dependencies_and_warnings():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert "Incoming dependencies" in content
        assert f"used by `{root / 'main.py'}` via `helper`" in content

        assert "Outgoing dependencies" in content
        assert f"depends on `{root / 'helper.py'}` via `helper`" in content

        assert "## Warnings" in content
        assert (
            f"`{root / 'main.py'}` has unresolved import "
            "`missing_module` at line `3`"
            in content
        )


def test_project_map_redacts_secret_like_graph_values():
    graph = {
        "schema_version": 1,
        "root": "repo",
        "files": [
            {
                "path": "src/config.py",
                "language": "python",
                "classes": [],
                "functions": [{"name": "load_config"}],
                "imports": ["requests"],
                "external_imports": ["requests"],
                "unresolved_imports": ["OPENAI_API_KEY=sk-testsecret-123456"],
                "unresolved_import_details": [
                    {"name": "OPENAI_API_KEY=sk-testsecret-123456", "line": 1}
                ],
                "routes": [],
            }
        ],
        "edges": [
            {
                "from": "src/app.py",
                "to": "src/config.py",
                "type": "imports",
                "import": "Authorization: Bearer sk-testsecret-123456",
            }
        ],
    }

    content = generate_project_map(graph)

    assert "sk-testsecret-123456" not in content
    assert "<redacted>" in content
    assert "src/config.py" in content


def test_project_map_preserves_macos_root_while_redacting_metadata():
    root = (
        "/private/var/folders/zz/"
        "aB3dE5fG7hJ9kL2mN4pQ6rS8tU0vW1xY2zA3bC4dE5fG6hI7jK8/T/repo"
    )
    secret = "sk-testsecret-123456"
    graph = {
        "schema_version": 1,
        "root": root,
        "files": [
            {
                "path": f"{root}/config.py",
                "language": "python",
                "classes": [],
                "functions": [],
                "imports": [f"API_KEY={secret}"],
                "external_imports": [],
                "unresolved_import_details": [],
                "routes": [],
            }
        ],
        "edges": [],
    }

    content = generate_project_map(graph)

    assert f"Project root: `{root}`" in content
    assert f"### `{root}/config.py`" in content
    assert secret not in content
    assert "API_KEY= <redacted>" in content


def test_cli_write_map_creates_project_map_file():
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_root = Path(temp_dir)
        repo_root = temp_root / "repo"
        _create_map_repo(repo_root)

        with change_directory(temp_root):
            exit_code, output = capture_output(write_map, str(repo_root))

        assert exit_code == 0
        assert (temp_root / ".aidc" / "graph.json").exists()
        assert (temp_root / ".aidc" / "project_map.md").exists()
        normalized_output = output.replace("\\", "/")

        assert "Strata" in output
        assert "Map complete" in output
        assert "Output" in output
        assert ".aidc/project_map.md" in normalized_output
        assert ".aidc/graph.json" in normalized_output
        assert "Root" in output
        assert "Files" in output
        assert "Edges" in output
        assert "Warnings" in output

        content = (temp_root / ".aidc" / "project_map.md").read_text(
            encoding="utf-8"
        )

        assert "# Project Map" in content
        assert str(repo_root / "helper.py") in content
        assert str(repo_root / "main.py") in content
        assert "missing_module" in content
        assert f"depends on `{repo_root / 'helper.py'}` via `helper`" in content


TESTS = [
    test_map_writer_core_import_matches_compatibility_shim,
    test_new_map_command_import_matches_legacy_shim,
    test_project_map_generation_includes_repo_summary,
    test_project_map_generation_includes_files_symbols_and_imports,
    test_project_map_generation_includes_dependencies_and_warnings,
    test_project_map_redacts_secret_like_graph_values,
    test_project_map_preserves_macos_root_while_redacting_metadata,
    test_cli_write_map_creates_project_map_file,
]
