import os

from cli import write_preflight
from preflight import generate_preflight_report, write_preflight_report
from tests.helpers import run_silently


def preflight_test_graph():
    return {
        "schema_version": 1,
        "root": "preflight_test_repo",
        "files": [
            {
                "path": "cli.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "main", "line": 1, "end_line": 10},
                    {"name": "write_map", "line": 12, "end_line": 20},
                ],
                "imports": ["map_writer"],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "map_writer.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "generate_project_map", "line": 1, "end_line": 10},
                    {"name": "write_project_map", "line": 12, "end_line": 20},
                ],
                "imports": [],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "tests/test_map_writer.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {
                        "name": "test_cli_write_map_creates_project_map_file",
                        "line": 1,
                        "end_line": 10,
                    },
                ],
                "imports": ["map_writer"],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "tests.py",
                "language": "python",
                "classes": [],
                "functions": [],
                "imports": ["tests.run"],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
        ],
        "edges": [
            {
                "from": "cli.py",
                "to": "map_writer.py",
                "type": "imports",
                "import": "map_writer",
            },
            {
                "from": "tests/test_map_writer.py",
                "to": "map_writer.py",
                "type": "imports",
                "import": "map_writer",
            },
            {
                "from": "tests.py",
                "to": "tests/run.py",
                "type": "imports",
                "import": "tests.run",
            },
        ],
    }


def test_generate_preflight_report_includes_main_sections():
    graph = preflight_test_graph()
    content = generate_preflight_report(graph, "add map command tests")

    assert "# Preflight Report" in content
    assert "Generated by Strata." in content
    assert "## Task" in content
    assert "## Repository Summary" in content
    assert "## Repository Health" in content
    assert "## Relevant Source Files" in content
    assert "## Relevant Test Files" in content
    assert "## Entry Points / Runners" in content
    assert "## Impact Notes" in content
    assert "## Verification Plan" in content
    assert "## AI Agent Instructions" in content


def test_generate_preflight_report_groups_relevant_files():
    graph = preflight_test_graph()
    content = generate_preflight_report(graph, "add map command tests")

    source_section_start = content.find("## Relevant Source Files")
    test_section_start = content.find("## Relevant Test Files")
    entrypoint_section_start = content.find("## Entry Points / Runners")

    assert source_section_start != -1
    assert test_section_start != -1
    assert entrypoint_section_start != -1

    assert source_section_start < test_section_start < entrypoint_section_start

    source_section = content[source_section_start:test_section_start]
    test_section = content[test_section_start:entrypoint_section_start]
    entrypoint_section = content[entrypoint_section_start:content.find("## Impact Notes")]

    assert "map_writer.py" in source_section
    assert "tests/test_map_writer.py" in test_section
    assert "cli.py" in entrypoint_section or "tests.py" in entrypoint_section


def test_generate_preflight_report_includes_relevant_files():
    graph = preflight_test_graph()
    content = generate_preflight_report(graph, "add map command tests")

    assert "tests/test_map_writer.py" in content
    assert "map_writer.py" in content
    assert "cli.py" in content
    assert "Relevance score" in content


def test_generate_preflight_report_includes_verification_plan():
    graph = preflight_test_graph()
    content = generate_preflight_report(graph, "add map command tests")

    assert "Recommended commands:" in content
    assert "`py tests.py`" in content
    assert "`py cli.py map tmp_repo`" in content
    assert "Likely related test files:" in content
    assert "tests/test_map_writer.py" in content


def test_write_preflight_report_creates_file():
    graph = preflight_test_graph()
    output_path = ".aidc/test_preflight.md"

    if os.path.exists(output_path):
        os.remove(output_path)

    write_preflight_report(graph, "add map command tests", output_path)

    assert os.path.exists(output_path)

    with open(output_path, "r", encoding="utf-8") as file:
        content = file.read()

    assert "# Preflight Report" in content
    assert "add map command tests" in content
    assert "## Verification Plan" in content


def test_cli_write_preflight_creates_preflight_file():
    exit_code = run_silently(write_preflight, ".", "add map command tests")

    assert exit_code == 0
    assert os.path.exists(".aidc/graph.json")
    assert os.path.exists(".aidc/preflight.md")

    with open(".aidc/preflight.md", "r", encoding="utf-8") as file:
        content = file.read()

    assert "# Preflight Report" in content
    assert "add map command tests" in content
    assert "## Repository Health" in content
    assert "## Relevant Source Files" in content
    assert "## Relevant Test Files" in content
    assert "## Entry Points / Runners" in content
    assert "## Impact Notes" in content
    assert "## Verification Plan" in content
    assert "## AI Agent Instructions" in content

def test_preflight_includes_backend_routes_section():
    graph = {
        "schema_version": 1,
        "root": "sample",
        "files": [
            {
                "path": "api.py",
                "language": "python",
                "imports": [],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
                "classes": [],
                "functions": [],
                "routes": [
                    {
                        "method": "GET",
                        "path": "/health",
                        "line": 1,
                        "source": "@app.get",
                    }
                ],
            },
            {
                "path": "routes/user.routes.ts",
                "language": "typescript",
                "imports": [],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
                "classes": [],
                "functions": [],
                "routes": [
                    {
                        "method": "POST",
                        "path": "/users",
                        "line": 8,
                        "source": "router.post",
                    }
                ],
            },
        ],
        "edges": [],
    }

    content = generate_preflight_report(graph, "change user API")

    assert "## Backend Routes" in content
    assert "- Backend routes: `2`" in content
    assert "| `GET` | `/health` | `api.py:1` | `@app.get` |" in content
    assert "| `POST` | `/users` | `routes/user.routes.ts:8` | `router.post` |" in content
    assert "Backend routes detected:" in content
    assert "- GET /health -> api.py:1" in content
    assert "- POST /users -> routes/user.routes.ts:8" in content
    assert "- Review backend routes if this task touches API behavior." in content


TESTS = [
    test_generate_preflight_report_includes_main_sections,
    test_generate_preflight_report_groups_relevant_files,
    test_generate_preflight_report_includes_relevant_files,
    test_generate_preflight_report_includes_verification_plan,
    test_write_preflight_report_creates_file,
    test_cli_write_preflight_creates_preflight_file,
    test_preflight_includes_backend_routes_section,
]