import os

from cli import write_map
from map_writer import generate_project_map
from scanner import scan_repo
from tests.helpers import run_silently


def test_project_map_generation_includes_repo_summary():
    graph = scan_repo("tmp_repo")
    content = generate_project_map(graph)

    assert "# Project Map" in content
    assert "Generated by Strata." in content
    assert "Project root: `tmp_repo`" in content
    assert "Schema version: `1`" in content
    assert "Files: `2`" in content
    assert "Dependency edges: `1`" in content


def test_project_map_generation_includes_files_symbols_and_imports():
    graph = scan_repo("tmp_repo")
    content = generate_project_map(graph)

    assert "tmp_repo\\helper.py" in content
    assert "tmp_repo\\main.py" in content

    assert "Functions: `help_user`" in content
    assert "Functions: `run`" in content
    assert "Classes: `App`" in content

    assert "Imports: `os`, `helper`, `missing_module`" in content
    assert "External imports: `os`" in content
    assert "Unresolved imports: `missing_module` at line `3`" in content


def test_project_map_generation_includes_dependencies_and_warnings():
    graph = scan_repo("tmp_repo")
    content = generate_project_map(graph)

    assert "Incoming dependencies" in content
    assert "used by `tmp_repo\\main.py` via `helper`" in content

    assert "Outgoing dependencies" in content
    assert "depends on `tmp_repo\\helper.py` via `helper`" in content

    assert "## Warnings" in content
    assert "`tmp_repo\\main.py` has unresolved import `missing_module` at line `3`" in content


def test_cli_write_map_creates_project_map_file():
    exit_code = run_silently(write_map, "tmp_repo")

    assert exit_code == 0
    assert os.path.exists(".aidc/graph.json")
    assert os.path.exists(".aidc/project_map.md")

    with open(".aidc/project_map.md", "r", encoding="utf-8") as file:
        content = file.read()

    assert "# Project Map" in content
    assert "tmp_repo\\helper.py" in content
    assert "tmp_repo\\main.py" in content
    assert "missing_module" in content
    assert "depends on `tmp_repo\\helper.py` via `helper`" in content


TESTS = [
    test_project_map_generation_includes_repo_summary,
    test_project_map_generation_includes_files_symbols_and_imports,
    test_project_map_generation_includes_dependencies_and_warnings,
    test_cli_write_map_creates_project_map_file,
]