import contextlib
import os
import tempfile
from pathlib import Path

from cli import write_map
from map_writer import generate_project_map
from scanner import scan_repo
from tests.helpers import capture_output


@contextlib.contextmanager
def change_directory(path: Path):
    original = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(original)


def _create_map_repo(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)

    (root / "helper.py").write_text(
        "class App:\n"
        "    pass\n\n"
        "def help_user():\n"
        "    return True\n",
        encoding="utf-8",
    )

    (root / "main.py").write_text(
        "import os\n"
        "import helper\n"
        "import missing_module\n\n"
        "def run():\n"
        "    return helper.help_user()\n",
        encoding="utf-8",
    )


def test_project_map_generation_includes_repo_summary():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert "# Project Map" in content
        assert "Generated by Strata." in content
        assert f"Project root: `{root}`" in content
        assert "Schema version: `1`" in content
        assert "Files: `2`" in content
        assert "Dependency edges: `1`" in content


def test_project_map_generation_includes_files_symbols_and_imports():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert f"{root}\\helper.py" in content
        assert f"{root}\\main.py" in content

        assert "Functions: `help_user`" in content
        assert "Functions: `run`" in content
        assert "Classes: `App`" in content

        assert "Imports: `os`, `helper`, `missing_module`" in content
        assert "External imports: `os`" in content
        assert "Unresolved imports: `missing_module` at line `3`" in content


def test_project_map_generation_includes_dependencies_and_warnings():
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "repo"
        _create_map_repo(root)

        graph = scan_repo(str(root))
        content = generate_project_map(graph)

        assert "Incoming dependencies" in content
        assert f"used by `{root}\\main.py` via `helper`" in content

        assert "Outgoing dependencies" in content
        assert f"depends on `{root}\\helper.py` via `helper`" in content

        assert "## Warnings" in content
        assert f"`{root}\\main.py` has unresolved import `missing_module` at line `3`" in content


def test_cli_write_map_creates_project_map_file():
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_root = Path(temp_dir)
        repo_root = temp_root / "repo"
        _create_map_repo(repo_root)

        with change_directory(temp_root):
            exit_code, output = capture_output(write_map, str(repo_root))

        assert exit_code == 0
        assert (temp_root / ".aidc" / "graph.json").exists()
        assert (temp_root / ".aidc" / "project_map.md").exists()
        normalized_output = output.replace("\\", "/")

        assert "Strata" in output
        assert "Map complete" in output
        assert "Output" in output
        assert ".aidc/project_map.md" in normalized_output
        assert ".aidc/graph.json" in normalized_output
        assert "Root" in output
        assert "Files" in output
        assert "Edges" in output
        assert "Warnings" in output

        content = (temp_root / ".aidc" / "project_map.md").read_text(
            encoding="utf-8"
        )

        assert "# Project Map" in content
        assert f"{repo_root}\\helper.py" in content
        assert f"{repo_root}\\main.py" in content
        assert "missing_module" in content
        assert f"depends on `{repo_root}\\helper.py` via `helper`" in content


TESTS = [
    test_project_map_generation_includes_repo_summary,
    test_project_map_generation_includes_files_symbols_and_imports,
    test_project_map_generation_includes_dependencies_and_warnings,
    test_cli_write_map_creates_project_map_file,
]
