import os

from brief import generate_task_brief, score_relevant_files
from cli import write_brief
from tests.helpers import capture_output, change_directory, temporary_repo


def brief_test_graph():
    return {
        "schema_version": 1,
        "root": "brief_test_repo",
        "files": [
            {
                "path": "cli.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "main", "line": 1, "end_line": 10},
                    {"name": "write_map", "line": 12, "end_line": 20},
                ],
                "imports": ["map_writer"],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "map_writer.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "generate_project_map", "line": 1, "end_line": 10},
                    {"name": "write_project_map", "line": 12, "end_line": 20},
                ],
                "imports": [],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "tests/test_map_writer.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "test_cli_write_map_creates_project_map_file", "line": 1, "end_line": 10},
                ],
                "imports": ["map_writer"],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
            {
                "path": "brief.py",
                "language": "python",
                "classes": [],
                "functions": [
                    {"name": "generate_task_brief", "line": 1, "end_line": 10},
                ],
                "imports": [],
                "external_imports": [],
                "unresolved_imports": [],
                "unresolved_import_details": [],
            },
        ],
        "edges": [
            {
                "from": "cli.py",
                "to": "map_writer.py",
                "type": "imports",
                "import": "map_writer",
            },
            {
                "from": "tests/test_map_writer.py",
                "to": "map_writer.py",
                "type": "imports",
                "import": "map_writer",
            },
        ],
    }


def test_task_brief_generation_includes_main_sections():
    graph = brief_test_graph()
    content = generate_task_brief(graph, "add map command tests")

    assert "# Task Brief" in content
    assert "Generated by Strata." in content
    assert "## Task" in content
    assert "add map command tests" in content
    assert "## Relevant Files" in content
    assert "## File Context" in content
    assert "## Impact Notes" in content
    assert "## Risks" in content
    assert "## Suggested Tests" in content
    assert "## Suggested Prompt for AI Agent" in content


def test_task_brief_relevance_for_map_command_tests_is_focused():
    graph = brief_test_graph()
    scored_files = score_relevant_files(graph, "add map command tests")

    selected_paths = [
        item["file"]["path"].replace("\\", "/")
        for item in scored_files[:3]
    ]

    selected_filenames = [
        os.path.basename(path)
        for path in selected_paths
    ]

    assert "tests/test_map_writer.py" in selected_paths
    assert "map_writer.py" in selected_filenames
    assert "cli.py" in selected_filenames
    assert "brief.py" not in selected_filenames


def test_task_brief_generation_includes_prompt_and_tests():
    graph = brief_test_graph()
    content = generate_task_brief(graph, "add map command tests")

    assert "Read these files first:" in content
    assert "tests/test_map_writer.py" in content
    assert "- map_writer.py" in content
    assert "- cli.py" in content

    assert "py tests.py" in content
    assert "py cli.py help" in content
    assert "py cli.py map" in content

    assert "Use only the Python standard library." in content
    assert "Do not touch unrelated files." in content


def test_cli_write_brief_creates_task_brief_file():
    with temporary_repo(
        {
            "cli.py": "def main():\n    return 0\n",
            "map_writer.py": "def generate_project_map(graph):\n    return ''\n",
            "tests/test_map_writer.py": (
                "def test_cli_write_map_creates_project_map_file():\n"
                "    pass\n"
            ),
            "brief.py": "def generate_task_brief(graph, task):\n    return ''\n",
        }
    ) as root:
        with change_directory(root):
            exit_code, output = capture_output(
                write_brief,
                str(root),
                "add map command tests",
            )

        assert exit_code == 0
        assert (root / ".aidc" / "graph.json").exists()
        assert (root / ".aidc" / "task_brief.md").exists()
        normalized_output = output.replace("\\", "/")

        assert "Strata" in output
        assert "Brief complete" in output
        assert "Task" in output
        assert "add map command tests" in output
        assert "Output" in output
        assert ".aidc/task_brief.md" in normalized_output
        assert ".aidc/graph.json" in normalized_output
        assert "Root" in output
        assert "Files" in output
        assert "Edges" in output
        assert "Warnings" in output

        with open(root / ".aidc" / "task_brief.md", "r", encoding="utf-8") as file:
            content = file.read()

        assert "# Task Brief" in content
        assert "add map command tests" in content
        assert "## Relevant Files" in content
        assert "## File Context" in content
        assert "## Impact Notes" in content
        assert "## Suggested Tests" in content
        assert "Suggested Prompt for AI Agent" in content


TESTS = [
    test_task_brief_generation_includes_main_sections,
    test_task_brief_relevance_for_map_command_tests_is_focused,
    test_task_brief_generation_includes_prompt_and_tests,
    test_cli_write_brief_creates_task_brief_file,
]
